In [71]:
import pandas as pd

In [ ]:
cidades = ["São Paulo (SP)",
           "Rio de Janeiro (RJ)",
           "Brasília (DF)",
           "Fortaleza (CE)",
           "Salvador (BA)",
           "Belo Horizonte (MG)",
           "Manaus (AM)",
           "Porto Alegre (RS)"
           ]

populacoes = [12,
              6.5,
              3,
              2.4,
              2.4,
              2.3,
              2,
              1.7
              ]

In [ ]:
cidades_s = pd.Series(cidades) #Cria a serie

cidades_s

0         São Paulo (SP)
1    Rio de Janeiro (RJ)
2          Brasília (DF)
3         Fortaleza (CE)
4          Salvador (BA)
5    Belo Horizonte (MG)
6            Manaus (AM)
7      Porto Alegre (RS)
dtype: str

In [74]:
pop = pd.Series(populacoes) #Cria a serie

pop

0    12.0
1     6.5
2     3.0
3     2.4
4     2.4
5     2.3
6     2.0
7     1.7
dtype: float64

In [75]:
cidades_s[7] #Pega o valor da posição informada

'Porto Alegre (RS)'

In [76]:
cidades_s[2:5] #Pega todos os valores dentro do range

2     Brasília (DF)
3    Fortaleza (CE)
4     Salvador (BA)
dtype: str

In [77]:
pop.max() #Pega o maior valor na serie

np.float64(12.0)

In [78]:
pop.mean() #Tira a média dos elementos na serie

np.float64(4.0375)

In [79]:
pop * 2 #Multiplica a serie por um valor
pop / 2 #Divide a serie por um valor
pop + 2 #Soma a serie com um valor
pop - 2 #Subtrai a serie de um valor

0    10.0
1     4.5
2     1.0
3     0.4
4     0.4
5     0.3
6     0.0
7    -0.3
dtype: float64

In [ ]:
capitais = pd.DataFrame({"Cidade": cidades_s, "População": pop})

capitais

                Cidade  População
0       São Paulo (SP)       12.0
1  Rio de Janeiro (RJ)        6.5
2        Brasília (DF)        3.0
3       Fortaleza (CE)        2.4
4        Salvador (BA)        2.4
5  Belo Horizonte (MG)        2.3
6          Manaus (AM)        2.0
7    Porto Alegre (RS)        1.7

In [81]:
capitais.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Cidade     8 non-null      str
 1   População  8 non-null      float64
dtypes: float64(1), str(1)
memory usage: 260.0 bytes

In [82]:
capitais["Cidade"]

capitais["População"]

0    12.0
1     6.5
2     3.0
3     2.4
4     2.4
5     2.3
6     2.0
7     1.7
Name: População, dtype: float64

In [83]:
capitais.iloc[3:7]

                Cidade  População
3       Fortaleza (CE)        2.4
4        Salvador (BA)        2.4
5  Belo Horizonte (MG)        2.3
6          Manaus (AM)        2.0

In [84]:
capitais.head()

capitais.tail()

                Cidade  População
3       Fortaleza (CE)        2.4
4        Salvador (BA)        2.4
5  Belo Horizonte (MG)        2.3
6          Manaus (AM)        2.0
7    Porto Alegre (RS)        1.7

In [85]:
capitais["População"].mean()

np.float64(4.0375)

In [ ]:
area_urbana = {
    914,
    640,
    590,
    253,
    196,
    274,
    277,
    336,
}

capitais ['Área Urbana em KM²'] = area_urbana

capitais

                Cidade  População
0       São Paulo (SP)       12.0
1  Rio de Janeiro (RJ)        6.5
2        Brasília (DF)        3.0
3       Fortaleza (CE)        2.4
4        Salvador (BA)        2.4
5  Belo Horizonte (MG)        2.3
6          Manaus (AM)        2.0
7    Porto Alegre (RS)        1.7